In [1]:
import numpy as np

In [10]:
t1 = np.arange(12)
print(t1)
t1.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(12,)

In [11]:
t2 = np.array([[1,2,3],[4,5,6]])
print(t2)
t2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

> - shape：纬度
> - np.arange：构建一维对象
> - np.array：构建对象

In [15]:
t3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)
t3.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [16]:
t4 = np.arange(12)
print(t4)
t4.reshape((3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

> - reshape((3,4))：构建（3，4）纬度对象

In [26]:
t5 = np.arange(24).reshape((2,3,4))
print(t5)
print("\n")
print(t5.reshape((4,6)))
print("\n")
print(t5)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [32]:
t5.flatten()
print(t5.shape[0]*t5.shape[1]*t5.shape[2])
t5.reshape((t5.shape[0]*t5.shape[1]*t5.shape[2],))

24


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

> - flatten()：展开成一维

In [33]:
t5+2

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [34]:
t5*2

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]])

In [35]:
t5/2

array([[[ 0. ,  0.5,  1. ,  1.5],
        [ 2. ,  2.5,  3. ,  3.5],
        [ 4. ,  4.5,  5. ,  5.5]],

       [[ 6. ,  6.5,  7. ,  7.5],
        [ 8. ,  8.5,  9. ,  9.5],
        [10. , 10.5, 11. , 11.5]]])

In [36]:
t5/0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[[nan, inf, inf, inf],
        [inf, inf, inf, inf],
        [inf, inf, inf, inf]],

       [[inf, inf, inf, inf],
        [inf, inf, inf, inf],
        [inf, inf, inf, inf]]])

In [37]:
t6 = np.arange(100,124).reshape((2,3,4))
t6

array([[[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123]]])

In [38]:
t5+t6

array([[[100, 102, 104, 106],
        [108, 110, 112, 114],
        [116, 118, 120, 122]],

       [[124, 126, 128, 130],
        [132, 134, 136, 138],
        [140, 142, 144, 146]]])

In [39]:
t5*t6

array([[[   0,  101,  204,  309],
        [ 416,  525,  636,  749],
        [ 864,  981, 1100, 1221]],

       [[1344, 1469, 1596, 1725],
        [1856, 1989, 2124, 2261],
        [2400, 2541, 2684, 2829]]])

In [40]:
t6/t5

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[[         inf, 101.        ,  51.        ,  34.33333333],
        [ 26.        ,  21.        ,  17.66666667,  15.28571429],
        [ 13.5       ,  12.11111111,  11.        ,  10.09090909]],

       [[  9.33333333,   8.69230769,   8.14285714,   7.66666667],
        [  7.25      ,   6.88235294,   6.55555556,   6.26315789],
        [  6.        ,   5.76190476,   5.54545455,   5.34782609]]])

In [43]:
t7 = np.arange(0,4)

In [44]:
t6-t7

array([[[100, 100, 100, 100],
        [104, 104, 104, 104],
        [108, 108, 108, 108]],

       [[112, 112, 112, 112],
        [116, 116, 116, 116],
        [120, 120, 120, 120]]])

In [48]:
t8 = np.arange(6).reshape(2,3,1)
t8

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [49]:
t6-t8

array([[[100, 101, 102, 103],
        [103, 104, 105, 106],
        [106, 107, 108, 109]],

       [[109, 110, 111, 112],
        [112, 113, 114, 115],
        [115, 116, 117, 118]]])

In [50]:
t9 = np.arange(10)
t9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
t6-t9

ValueError: operands could not be broadcast together with shapes (2,3,4) (10,) 

In [ ]:
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"
uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"
t1 = np.loadtxt(us_file_path,delimiter=",",dtype="int",unpack=True)

> - delimiter：分割方式
> - dtype：指定类型
> - unpack：旋转矩阵（转秩）

In [ ]:
t = np.arange(24).reshape((4,6))
print(t < 10)
t[t<10] = 0
t

In [ ]:
np.where(t<10,0,10)

- 小于10 的替换成0
- 大于等于10 替换成10

In [ ]:
t.clip(10,18)

- 小于10 替换成10
- 大于18 替换成18

In [ ]:
np.vstack((t,t1))
np.vsplit((t,t1))

- vstack 竖直拼接
- vsplit 水平拼接
## t t1 行或列同纬度

In [ ]:
us_data = "./youtube_video_data/US_video_data_numbers.csv"
uk_data = "./youtube_video_data/GB_video_data_numbers.csv"

# 加载国家数据
us_data = np.loadtxt(us_data, delimiter=",", dtype=int)
uk_data = np.loadtxt(uk_data, delimiter=",", dtype=int)

# 添加国家信息
# 构造全为0的数据
zeros_data = np.zeros((us_data.shape[0], 1)).astype(int)
ones_data = np.ones((uk_data.shape[0], 1)).astype(int)

# 分别添加一列全为0,1的数组
us_data = np.hstack((us_data, zeros_data))
uk_data = np.hstack((uk_data, ones_data))

# 拼接两组数据
final_data = np.vstack((us_data, uk_data))

- np.zeros 构建一列0数据
- np.ones 构建一列1数据
- np.hstack 添加一列数据

In [ ]:
np.eye(10)

- 方阵

In [ ]:
np.argmax(t,axis=0) # 列
np.argmin(t,axis=1) # 行

- 最大值位置
- 最小值位置

In [ ]:
t=t1
t=t1[:]
t=t1.copy()

In [ ]:
np.count_nonzero(t2)
np.isnan(t2)

- 不为零的个数
- 是nan