In [91]:
from tensorflow import keras
import tensorflow as tf

- 载入手写数据集

In [92]:
(x, y), (x_test, y_test) = keras.datasets.mnist.load_data()

- 数据维度

In [93]:
print(x.shape)
print(y.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


- 大小值

In [94]:
print('min:' + str(x.min()))
print('max:' + str(x.max()))

min:0
max:255


In [95]:
y[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

- 独热码

In [96]:
y_onehot = tf.one_hot(y, depth=10)
y_onehot[:2]

<tf.Tensor: id=400385, shape=(2, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

- 载入cifar10数据集

In [97]:
(x, y), (x_test, y_test) = keras.datasets.cifar10.load_data()

In [112]:
print(x.shape)
print(y.shape)
print(x_test.shape)
print(y_test.shape)

(50000, 32, 32, 3)
(1, 10)
(10000, 32, 32, 3)
(10000, 1)


- numpy转TensorShape

In [98]:
db1 = tf.data.Dataset.from_tensor_slices((x_test, y_test))
db = tf.data.Dataset.from_tensor_slices(x_test)

In [99]:
print(next(iter(db1))[1].shape)
print(next(iter(db)).shape)

(1,)
(32, 32, 3)


In [100]:
db2, db3 = next(iter(db1))

In [101]:
print(db3.shape)
print(db2.shape)


(1,)
(32, 32, 3)


In [102]:
print(next(iter(db1)))
print(type(next(iter(db1))))

(<tf.Tensor: id=400416, shape=(32, 32, 3), dtype=uint8, numpy=
array([[[158, 112,  49],
        [159, 111,  47],
        [165, 116,  51],
        ...,
        [137,  95,  36],
        [126,  91,  36],
        [116,  85,  33]],

       [[152, 112,  51],
        [151, 110,  40],
        [159, 114,  45],
        ...,
        [136,  95,  31],
        [125,  91,  32],
        [119,  88,  34]],

       [[151, 110,  47],
        [151, 109,  33],
        [158, 111,  36],
        ...,
        [139,  98,  34],
        [130,  95,  34],
        [120,  89,  33]],

       ...,

       [[ 68, 124, 177],
        [ 42, 100, 148],
        [ 31,  88, 137],
        ...,
        [ 38,  97, 146],
        [ 13,  64, 108],
        [ 40,  85, 127]],

       [[ 61, 116, 168],
        [ 49, 102, 148],
        [ 35,  85, 132],
        ...,
        [ 26,  82, 130],
        [ 29,  82, 126],
        [ 20,  64, 107]],

       [[ 54, 107, 160],
        [ 56, 105, 149],
        [ 45,  89, 132],
        ...,
        [ 2

In [103]:
def preprocess(x, y):
    x = tf.cast(x, dtype=tf.float64)/255.
    y = tf.cast(y, dtype=tf.int32)
    y = tf.one_hot(y, depth=10)
    return x, y

- 数据整理

In [104]:
db2 = db1.map(preprocess)

In [105]:
res = next(iter(db2))
print(res[0].shape, res[1].shape)

(32, 32, 3) (1, 10)


In [106]:
res[1]

<tf.Tensor: id=400446, shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

- 一次拿32个

In [107]:
db3 = db2.batch(32)

In [108]:
res = next(iter(db3))

In [109]:
print(res[0].shape, res[1].shape)

(32, 32, 32, 3) (32, 1, 10)


- 整个数据集迭代次数10

In [110]:
db4 = db2.repeat(10)