In [1]:
import tensorflow as tf

In [6]:
x = tf.fill([3,3], 3)
x

<tf.Tensor: id=14, shape=(3, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [7]:
# 平均值
tf.reduce_mean(x)

<tf.Tensor: id=16, shape=(), dtype=int32, numpy=3>

In [8]:
# 平方
tf.square(x)

<tf.Tensor: id=17, shape=(3, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]], dtype=int32)>

In [16]:
# 升维
print(tf.broadcast_to(x, [2, 3, 3]))

tf.Tensor(
[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]], shape=(2, 3, 3), dtype=int32)


In [29]:
x = tf.random.uniform([2, 10])
print(x)
x = tf.cast(x, dtype=tf.float32)
# 指定维度概率和归一
prob = tf.nn.softmax(x, axis=1)
print(prob)

tf.Tensor(
[[0.6274221  0.07920444 0.3156935  0.6167258  0.93109655 0.5665889
  0.93229806 0.7558341  0.88532877 0.19120777]
 [0.11493814 0.4044317  0.5013703  0.9776138  0.15911674 0.9285929
  0.15173364 0.36369848 0.41529977 0.2379129 ]], shape=(2, 10), dtype=float32)
tf.Tensor(
[[0.09970583 0.05762788 0.07300264 0.09864503 0.13508426 0.0938212
  0.13524665 0.11336766 0.12904109 0.06445774]
 [0.070031   0.09354397 0.10306606 0.16593792 0.07319424 0.15799965
  0.07265583 0.08981019 0.09456616 0.07919496]], shape=(2, 10), dtype=float32)


In [30]:
pred = tf.argmax(prob, axis=1)
print(pred)

tf.Tensor([6 3], shape=(2,), dtype=int64)


In [34]:
idx = tf.range(4)
idx = tf.random.shuffle(idx)
print(idx)
a = tf.random.uniform([4, 2])
b = tf.random.uniform([2, 4])
c = tf.random.uniform([2, 4, 2])
print(a, b, c)
print(tf.gather(a, idx, axis=0), tf.gather(b, idx, axis=1), tf.gather(c, idx, axis=1))

tf.Tensor([3 0 2 1], shape=(4,), dtype=int32)
tf.Tensor(
[[0.12924731 0.4669721 ]
 [0.6266304  0.8616588 ]
 [0.22807884 0.6922176 ]
 [0.8769388  0.3559326 ]], shape=(4, 2), dtype=float32) tf.Tensor(
[[0.08034086 0.17933714 0.6963326  0.6739634 ]
 [0.7874595  0.6543771  0.93194294 0.13772213]], shape=(2, 4), dtype=float32) tf.Tensor(
[[[0.34034598 0.06492841]
  [0.18149757 0.47438645]
  [0.5667715  0.5947113 ]
  [0.19636941 0.68866277]]

 [[0.77917767 0.42270613]
  [0.961926   0.7967477 ]
  [0.2778368  0.04137683]
  [0.5966625  0.22719026]]], shape=(2, 4, 2), dtype=float32)
tf.Tensor(
[[0.8769388  0.3559326 ]
 [0.12924731 0.4669721 ]
 [0.22807884 0.6922176 ]
 [0.6266304  0.8616588 ]], shape=(4, 2), dtype=float32) tf.Tensor(
[[0.6739634  0.08034086 0.6963326  0.17933714]
 [0.13772213 0.7874595  0.93194294 0.6543771 ]], shape=(2, 4), dtype=float32) tf.Tensor(
[[[0.19636941 0.68866277]
  [0.34034598 0.06492841]
  [0.5667715  0.5947113 ]
  [0.18149757 0.47438645]]

 [[0.5966625  0.22719026]