In [1]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

In [2]:
a = tf.reshape(tf.range(9), [3, 3])
a

<tf.Tensor: id=5, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [3]:
tf.pad(a, [[1, 1], [1, 0]]) # [[上, 下], [左, 右]] 与维度映射

<tf.Tensor: id=7, shape=(5, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 1, 2],
       [0, 3, 4, 5],
       [0, 6, 7, 8],
       [0, 0, 0, 0]], dtype=int32)>

In [6]:
a = tf.random.normal([4, 28, 28, 3])
a.shape

TensorShape([4, 28, 28, 3])

In [7]:
tf.pad(a, [[0, 0], [1, 1], [1, 1], [0, 0]]).shape # 填充

TensorShape([4, 30, 30, 3])

In [9]:
a = tf.reshape(tf.range(9), [3, 3])
print(tf.tile(a, [1, 2])) # [1, 2] 对应维度复制次数
print(tf.tile(a, [2, 2]))

tf.Tensor(
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]], shape=(3, 6), dtype=int32)
tf.Tensor(
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]], shape=(6, 6), dtype=int32)


In [15]:
tf.broadcast_to(a, [3, 3])

<tf.Tensor: id=48, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>