In [1]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

In [3]:
a = tf.random.shuffle(tf.range(5))
# print(tf.sort(a))
print(tf.sort(a, direction='DESCENDING')) # DESCENDING 逆序 大-小

tf.Tensor([4 3 2 1 0], shape=(5,), dtype=int32)


In [7]:
# print(tf.argsort(a, direction='DESCENDING'))
idx = tf.argsort(a)
print(tf.argsort(a)) # 排序的下标 小-大

tf.Tensor([1 4 3 0 2], shape=(5,), dtype=int32)


In [8]:
print(tf.gather(a, idx)) # 按下标排列

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [9]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)

In [11]:
a

<tf.Tensor: id=85, shape=(3, 3), dtype=int32, numpy=
array([[2, 1, 4],
       [8, 4, 2],
       [2, 0, 5]], dtype=int32)>

In [12]:
tf.sort(a)

<tf.Tensor: id=96, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [2, 4, 8],
       [0, 2, 5]], dtype=int32)>

In [13]:
idx = tf.argsort(a)
idx

<tf.Tensor: id=106, shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 2],
       [2, 1, 0],
       [1, 0, 2]], dtype=int32)>

### top_k 返回前几个的值与下标

In [15]:
res = tf.math.top_k(a, 2)
res

TopKV2(values=<tf.Tensor: id=111, shape=(3, 2), dtype=int32, numpy=
array([[4, 2],
       [8, 4],
       [5, 2]], dtype=int32)>, indices=<tf.Tensor: id=112, shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [0, 1],
       [2, 0]], dtype=int32)>)