In [1]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

In [2]:
(x, y), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
print(x.shape)
print(y.shape)
print(x.min(), x.max(), x.mean())

(60000, 28, 28)
(60000,)
0 255 33.318421449829934


In [3]:
x_test.shape, y_test.shape

((10000, 28, 28), (10000,))

In [7]:
y_onehot = tf.one_hot(y, depth=10)
y_onehot[:2]

<tf.Tensor: id=26, shape=(2, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [6]:
y[:4]

array([5, 0, 4, 1], dtype=uint8)

In [14]:
(x, y), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
print(x.shape)
print(y.shape)
print(x.min(), x.max(), x.mean())
print(y[:4])

(50000, 32, 32, 3)
(50000, 1)
0 255 120.70756512369792
[[6]
 [9]
 [9]
 [4]]


In [12]:
(x, y), (x_test, y_test) = tf.keras.datasets.cifar100.load_data()
print(x.shape)
print(y.shape)
print(x.min(), x.max(), x.mean())
print(y[:4])

(50000, 32, 32, 3)
(50000, 1)
0 255 121.936059453125
[[19]
 [29]
 [ 0]
 [11]]


In [15]:
db = tf.data.Dataset.from_tensor_slices(x_test)
next(iter(db))

<tf.Tensor: id=43, shape=(32, 32, 3), dtype=uint8, numpy=
array([[[158, 112,  49],
        [159, 111,  47],
        [165, 116,  51],
        ...,
        [137,  95,  36],
        [126,  91,  36],
        [116,  85,  33]],

       [[152, 112,  51],
        [151, 110,  40],
        [159, 114,  45],
        ...,
        [136,  95,  31],
        [125,  91,  32],
        [119,  88,  34]],

       [[151, 110,  47],
        [151, 109,  33],
        [158, 111,  36],
        ...,
        [139,  98,  34],
        [130,  95,  34],
        [120,  89,  33]],

       ...,

       [[ 68, 124, 177],
        [ 42, 100, 148],
        [ 31,  88, 137],
        ...,
        [ 38,  97, 146],
        [ 13,  64, 108],
        [ 40,  85, 127]],

       [[ 61, 116, 168],
        [ 49, 102, 148],
        [ 35,  85, 132],
        ...,
        [ 26,  82, 130],
        [ 29,  82, 126],
        [ 20,  64, 107]],

       [[ 54, 107, 160],
        [ 56, 105, 149],
        [ 45,  89, 132],
        ...,
        [ 24,  7

In [16]:
db = tf.data.Dataset.from_tensor_slices((x_test, y_test))
print(next(iter(db)))

(<tf.Tensor: id=52, shape=(32, 32, 3), dtype=uint8, numpy=
array([[[158, 112,  49],
        [159, 111,  47],
        [165, 116,  51],
        ...,
        [137,  95,  36],
        [126,  91,  36],
        [116,  85,  33]],

       [[152, 112,  51],
        [151, 110,  40],
        [159, 114,  45],
        ...,
        [136,  95,  31],
        [125,  91,  32],
        [119,  88,  34]],

       [[151, 110,  47],
        [151, 109,  33],
        [158, 111,  36],
        ...,
        [139,  98,  34],
        [130,  95,  34],
        [120,  89,  33]],

       ...,

       [[ 68, 124, 177],
        [ 42, 100, 148],
        [ 31,  88, 137],
        ...,
        [ 38,  97, 146],
        [ 13,  64, 108],
        [ 40,  85, 127]],

       [[ 61, 116, 168],
        [ 49, 102, 148],
        [ 35,  85, 132],
        ...,
        [ 26,  82, 130],
        [ 29,  82, 126],
        [ 20,  64, 107]],

       [[ 54, 107, 160],
        [ 56, 105, 149],
        [ 45,  89, 132],
        ...,
        [ 24,  

In [17]:
# 打散
db = db.shuffle(10000)

In [18]:
# 数据预处理
def preproxess(x, y):
    # cast 类型转换
    x = tf.cast(x, dtype=tf.float32) / 255
    y = tf.cast(y, dtype=tf.int32)
    y = tf.one_hot(y, depth=10)
    return x, y

db2 = db.map(preproxess)
res = next(iter(db2))
res[0].shape, res[1].shape

(TensorShape([32, 32, 3]), TensorShape([1, 10]))

In [19]:
res[1][:2]

<tf.Tensor: id=85, shape=(1, 10), dtype=float32, numpy=array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:

db3 = db2.batch(32)
res = next(iter(db3))
res[0].shape, res[1].shape

(TensorShape([32, 32, 32, 3]), TensorShape([32, 1, 10]))

In [21]:
x = tf.random.normal([3,3])

In [22]:
x

<tf.Tensor: id=101, shape=(3, 3), dtype=float32, numpy=
array([[ 1.4471945 , -2.0056868 , -0.02623525],
       [-0.50294054,  2.6745224 ,  0.21915592],
       [ 0.39725196, -1.0755213 ,  0.2782927 ]], dtype=float32)>

In [23]:
tf.random.shuffle(x)

<tf.Tensor: id=102, shape=(3, 3), dtype=float32, numpy=
array([[ 0.39725196, -1.0755213 ,  0.2782927 ],
       [ 1.4471945 , -2.0056868 , -0.02623525],
       [-0.50294054,  2.6745224 ,  0.21915592]], dtype=float32)>

In [ ]:
# 例子
def preproxess(x, y):
    # cast 类型转换
    x = tf.cast(x, dtype=tf.float32) / 255
    y = tf.cast(y, dtype=tf.int32)
    return x, y

def mnist_dataset():
    (x, y), (x_val, y_val) = tf.keras.datasets.fashion_mnist.load_data()
    y = tf.one_hot(y, depth=10)
    y_val = tf.one_hot(y_val, depth=10)
    
    ds = tf.data.Dataset.from_tensor_slices((x, y))
    ds = ds.map(preproxess)
    ds = ds.shuffle(60000).batch(100)
    ds_val = tf.data.Dataset.from_tensor_slices((x_val, y_val))
    ds_val = ds_val.map(preproxess)
    ds_val = ds_val.shuffle(10000).batch(100)
    return ds, ds_val