In [3]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

### 数据读取

In [20]:
e = tf.data.Dataset.from_tensor_slices([1, 2, 3])
e

<TensorSliceDataset shapes: (), types: tf.int32>

In [36]:
aa = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4])
aa = aa.filter(lambda x:x < 2)
print(aa)

<FilterDataset shapes: (), types: tf.int32>


In [43]:
a = tf.data.Dataset.from_tensor_slices([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

for i in a.take(3):
    print(i)
for i in a.take(1):
    print(i)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [40]:
a.shard

<bound method DatasetV2.shard of <TensorSliceDataset shapes: (3,), types: tf.int32>>

### Tensor

In [1]:
import tensorflow as tf

In [3]:
print(tf.constant(1))
print(tf.constant(1.))
# print(tf.constant(2.2, dtype=tf.int32)) 报错
print(tf.constant(2., dtype=tf.double))
print(tf.constant([True, False]))
print(tf.constant('ok!'))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float64)
tf.Tensor([ True False], shape=(2,), dtype=bool)
tf.Tensor(b'ok!', shape=(), dtype=string)


### CPU

In [4]:
with tf.device("cpu"):
    a = tf.constant([1])

In [5]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

### GPU

In [16]:
with tf.device("GPU"):
    b = tf.constant([[1, 2, 3], [4, 5, 6]])

In [7]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

### GPU <=> CPU

In [8]:
a.gpu()
b.cpu()

Instructions for updating:
Use tf.identity instead.
Instructions for updating:
Use tf.identity instead.


<tf.Tensor: id=11, shape=(), dtype=int32, numpy=4>

In [17]:
b.ndim # b.shape

2

In [19]:
tf.rank(b)

<tf.Tensor: id=15, shape=(), dtype=int32, numpy=2>

In [18]:
b.name

AttributeError: Tensor.name is meaningless when eager execution is enabled.

### 判断是否是Tensor

In [24]:
print(tf.is_tensor(a))
print(isinstance(a, tf.Tensor)) # 
import numpy as np
d = np.arange(4)
print(tf.is_tensor(d))

True
True
False


In [25]:
a.dtype == tf.float16

False

In [26]:
d.dtype

dtype('int64')

### numpy转换Tensor

In [29]:
# dd = tf.convert_to_tensor(d) 默认numpy是int64
dd = tf.convert_to_tensor(d, dtype=tf.int32) # 转int32
dd

<tf.Tensor: id=18, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

### Tensor 转换 dtype

In [32]:
dd = tf.cast(dd, dtype=tf.float32)
print(dd) # int32 转 float32
dd = tf.cast(dd, dtype=tf.double)
print(dd) # float32 转 float64
dd = tf.cast(dd, dtype=tf.int32)
print(dd) # float64 转 int32

tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32)
tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


### Variable

In [34]:
a = tf.range(5)
# b = tf.Variable(a)
b = tf.Variable(a, name='input_data')
print(b.dtype)
print(b.name)

<dtype: 'int32'>
input_data:0


In [38]:
print(isinstance(b, tf.Tensor))
print(isinstance(b, tf.Variable))
print(tf.is_tensor(b))

False
True
True


### 取得数据

In [40]:
print(b.numpy()) # 返回numpy数据
a = tf.ones([])
print(int(a)) 
print(float(a))

[0 1 2 3 4]
1
1.0


### 创建Tensor

In [2]:
w1 = tf.Variable(tf.zeros(10))
w1

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [6]:
b1 = tf.constant([1, 2, 3])
b1

<tf.Tensor: id=57, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [8]:
b2 = tf.broadcast_to(b1, [2, 3])
b2

<tf.Tensor: id=60, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

### broadcast_to广播

In [10]:
b3 = tf.broadcast_to(b1, [3, 2, 3])
b3

<tf.Tensor: id=64, shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

### tf.zeros、tf.ones

In [41]:
print(tf.zeros([]))
print(tf.zeros([1]))
print(tf.zeros([2, 2]))
print(tf.zeros([2, 2, 3]))

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


### tf.zeros_like、tf.ones_like

In [42]:
a = tf.zeros([2, 2, 3])
print(tf.zeros_like(a))
print(tf.zeros_like(a.shape))

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)


### tf.fill 自定义填充

In [44]:
print(tf.fill([2, 2], 9))

tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


### 正太分布初始化

In [46]:
print(tf.random.normal([2, 2], mean=1, stddev=1)) #mean 平均数, stddev 标准差
print(tf.random.truncated_normal([2, 2], mean=0, stddev=1)) # 截断分布
print(tf.random.uniform([2, 2], minval=0, maxval=100)) # 均匀分布

tf.Tensor(
[[ 0.53010046  2.5945115 ]
 [-0.20950401 -0.06755352]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.6677093  -1.6080464 ]
 [-0.8025701   0.41457698]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[80.53129   44.91074  ]
 [ 6.6080093 17.574097 ]], shape=(2, 2), dtype=float32)


### 随机打散

In [47]:
idx = tf.range(10)
print(idx)
idx = tf.random.shuffle(idx)
print(idx)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([7 6 8 5 9 1 2 3 0 4], shape=(10,), dtype=int32)


In [49]:
a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)
print(a)
print(b)

tf.Tensor(
[[-0.23932256  0.5528639   0.16717792 ... -0.53146416  0.4687923
   0.19810356]
 [-2.7161212   0.22025712  1.1668127  ...  1.3325884  -0.08589137
  -0.37005424]
 [-1.25011     0.07619333  1.3757708  ...  1.4364158  -1.3163306
  -0.63596123]
 ...
 [ 1.0448921   0.32109106 -2.5156832  ...  0.8137729  -0.17724657
  -0.42604956]
 [-0.3530785  -0.57427406  0.5930358  ...  0.6514702  -2.0582414
  -0.63689774]
 [ 1.7052666   1.7266797  -0.7647951  ... -0.2878193   1.614691
   1.4580098 ]], shape=(10, 784), dtype=float32)
tf.Tensor([8 9 2 4 6 5 0 1 5 7], shape=(10,), dtype=int32)


In [50]:
a = tf.gather(a, idx) # 根据idx顺序打乱
b = tf.gather(b, idx) 
print(a)
print(b)

tf.Tensor(
[[ 1.0448921   0.32109106 -2.5156832  ...  0.8137729  -0.17724657
  -0.42604956]
 [ 1.729102   -1.0700284  -0.50810707 ...  1.4955803  -0.05545609
  -0.3870785 ]
 [-0.3530785  -0.57427406  0.5930358  ...  0.6514702  -2.0582414
  -0.63689774]
 ...
 [ 1.3186626   1.0876559  -0.5206251  ... -1.729692   -0.08036444
   0.6359166 ]
 [-0.23932256  0.5528639   0.16717792 ... -0.53146416  0.4687923
   0.19810356]
 [ 0.6000704   0.6706777  -0.3903356  ...  0.56313694 -2.4014735
  -1.609817  ]], shape=(10, 784), dtype=float32)
tf.Tensor([1 0 5 5 7 9 2 4 8 6], shape=(10,), dtype=int32)


### 例子

In [55]:
out = tf.random.uniform([4, 10])
print('out::', out)
y = tf.range(4)
print('y::', y)
y = tf.one_hot(y, depth=10)
print('y_one_hot::', y)
loss = tf.keras.losses.mse(y, out)
print('loss::', loss)
loss = tf.reduce_mean(loss)
print('loss::', loss)

net = tf.keras.layers.Dense(10)
net.build((4, 8))
print('kernel::', net.kernel)
print('bias::', net.bias)

out:: tf.Tensor(
[[6.64748311e-01 1.23494506e-01 4.62478757e-01 9.88028884e-01
  6.24939203e-02 3.18114758e-01 7.46607780e-04 4.73524213e-01
  3.03321600e-01 7.56509423e-01]
 [4.51095104e-01 7.94083714e-01 1.95187092e-01 5.79916716e-01
  7.90974736e-01 7.34602928e-01 4.73613024e-01 5.33862114e-01
  1.08892202e-01 6.92363381e-01]
 [4.01445746e-01 4.32389855e-01 3.10505629e-02 3.88933182e-01
  4.24783111e-01 9.42399859e-01 1.20945334e-01 3.72165084e-01
  8.67015719e-01 5.63768268e-01]
 [9.39841747e-01 1.00030184e-01 5.68107367e-01 5.40875673e-01
  3.87887955e-02 8.86734605e-01 7.33650804e-01 3.47228646e-01
  2.95575023e-01 5.38298130e-01]], shape=(4, 10), dtype=float32)
y:: tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
y_one_hot:: tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)
loss:: tf.Tensor([0.23113708 0.27861148 0.37294954 0.32505932], shape=(4,), dtype=floa

In [56]:
x = tf.random.normal([4, 784])
print('x::', x)
net = tf.keras.layers.Dense(10)
print('build::', net.build)
print('shape::', net(x).shape)
print('kernel_shape::', net.kernel.shape) # w
print('bias_shape::', net.bias.shape) # b

x:: tf.Tensor(
[[-0.20230982 -0.740376   -0.8560114  ... -0.6147968  -0.5590666
   0.46283954]
 [-0.84817666 -0.45194694  0.20332024 ... -0.70844024 -1.7263876
   2.0687895 ]
 [-2.1870463  -0.26474497  1.761193   ... -0.9294991   0.5637731
   0.69962263]
 [ 0.36525223 -2.7098393   1.6137484  ...  2.3393362  -0.02364289
   0.25326854]], shape=(4, 784), dtype=float32)
build:: <bound method Dense.build of <tensorflow.python.keras.layers.core.Dense object at 0x7fc7b5c9a2b0>>
shape:: (4, 10)
kernel_shape:: (784, 10)
bias_shape:: (10,)
