In [1]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

In [6]:
a = tf.ones([2, 2])
print(tf.norm(a)) # norm 二范数计算
print(tf.square(a)) # square 各自平方
print(tf.reduce_sum([[1, 2], [3, 4]])) # reduce_sum 全部求和
print(tf.sqrt(tf.reduce_sum(tf.square(a))))

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [3]:
print(tf.norm(a, ord=2, axis=0)) # ord = 2 二范数， = 1 一范数; axis 计算的维度
print(tf.norm(a, ord=1, axis=0))
print(tf.norm(a, ord=1))

tf.Tensor([1.4142135 1.4142135], shape=(2,), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


### min/max/mean

In [16]:
a = tf.random.normal([4, 10])
print(tf.reduce_min(a), tf.reduce_max(a), tf.reduce_mean(a))
print(tf.reduce_min(a, axis=0), tf.reduce_max(a, axis=0), tf.reduce_mean(a, axis=0)) # 按axis维度判别

tf.Tensor(-1.8554432, shape=(), dtype=float32) tf.Tensor(2.868143, shape=(), dtype=float32) tf.Tensor(-0.072711535, shape=(), dtype=float32)
tf.Tensor(
[-0.91660374 -0.7569457  -1.1649489  -0.7549451  -0.93924606 -1.8554432
 -1.6354672  -0.69143933 -1.509856   -0.97375596], shape=(10,), dtype=float32) tf.Tensor(
[0.28357294 1.3459109  1.9424527  1.3843846  2.868143   0.2985655
 1.4510401  0.06139847 0.857607   0.03887277], shape=(10,), dtype=float32) tf.Tensor(
[-0.39120507  0.15587378  0.18531549  0.14873765  0.7145338  -0.62698233
 -0.23693308 -0.35093623 -0.00544402 -0.32007542], shape=(10,), dtype=float32)


In [17]:
print(tf.argmax(a).shape) # 最大值位置
print(tf.argmax(a))
print(tf.argmin(a).shape)

(10,)
tf.Tensor([2 3 3 0 0 1 2 1 0 3], shape=(10,), dtype=int64)
(10,)


In [22]:
a = tf.constant([1, 2, 3, 3, 4])
b = tf.range(5)
print(tf.equal(a, b)) # 判断是否相等返回Tensor
res = tf.equal(a, b)
print(tf.cast(res, dtype=tf.int32)) # 转换数据类型为int
print(tf.reduce_sum(tf.cast(res, dtype=tf.int32)))

tf.Tensor([False False False  True  True], shape=(5,), dtype=bool)
tf.Tensor([0 0 0 1 1], shape=(5,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [23]:
a

<tf.Tensor: id=213, shape=(5,), dtype=int32, numpy=array([1, 2, 3, 3, 4], dtype=int32)>

In [29]:
a = tf.random.normal([2, 3])
a

<tf.Tensor: id=239, shape=(2, 3), dtype=float32, numpy=
array([[-0.86742175,  0.3751898 , -0.9536958 ],
       [ 0.44455117,  0.25821716,  1.2701343 ]], dtype=float32)>

In [30]:
tf.argmax(a, axis=0)

<tf.Tensor: id=241, shape=(3,), dtype=int64, numpy=array([1, 0, 1])>

### 去重

In [31]:
a = tf.constant([1, 2, 2, 4, 5])
print(tf.unique(a))

Unique(y=<tf.Tensor: id=243, shape=(4,), dtype=int32, numpy=array([1, 2, 4, 5], dtype=int32)>, idx=<tf.Tensor: id=244, shape=(5,), dtype=int32, numpy=array([0, 1, 1, 2, 3], dtype=int32)>)
