In [1]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'
a = tf.ones([1, 5, 5, 3])
print(a[0][0])
print(a[0][0][0])
print(a[0][0][0][2])

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [4]:
a = tf.random.normal([4, 28, 28, 3])
print(a[1].shape)
print(a[1, 2, 3].shape)
print(a[1, 2, 3, 2].shape)

(28, 28, 3)
(3,)
()


In [5]:
a = tf.range(10)
print(a[-1:])
print(a[-2:])
print(a[:2])
print(a[:1])
print(a[:-1])

tf.Tensor([9], shape=(1,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([0], shape=(1,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


### tf.gather

In [7]:
a = tf.random.normal([4, 35, 8])
print(tf.gather(a, axis=0, indices=[2, 3]).shape) # axis 维度
print(tf.gather(a, axis=0, indices=[2, 1, 3, 0]).shape)
print(tf.gather(a, axis=1, indices=[2, 3, 7, 9, 16]).shape)
print(tf.gather(a, axis=2, indices=[2, 3, 7]).shape)

(2, 35, 8)
(4, 35, 8)
(4, 5, 8)
(4, 35, 3)


### tf.gather_nd

In [3]:
a = tf.random.normal([2, 4, 8])
print(a)
print(tf.gather_nd(a, [0]).shape)
print(tf.gather_nd(a, [0, 1]).shape)
print(tf.gather_nd(a, [0, 1, 2]).shape)
print(tf.gather_nd(a, [[0, 1, 2]]).shape)
print(tf.gather_nd(a, [0]))
print(tf.gather_nd(a, [0, 1]))
print(tf.gather_nd(a, [0, 1, 2]))
print(tf.gather_nd(a, [[0, 1, 2]]))

tf.Tensor(
[[[-0.09535595 -1.3481662  -0.44069862 -1.4237616   1.3450791
    1.1235632  -1.9858646   1.0657926 ]
  [-0.14793572  0.21747819 -1.6281852   1.337452   -0.43633217
    0.9102865   1.0791811   1.4007689 ]
  [-0.9875471  -0.9965379  -0.3495302   1.2075344   0.12781546
   -0.8592757   1.6788639  -0.6817214 ]
  [-0.13740075  1.4901042   1.3103049  -1.2123821  -0.3173167
    1.083988   -0.11318804 -0.90810645]]

 [[ 1.2613294  -1.3819859   0.16758442 -0.4370513   0.02184424
   -1.0311811  -0.08914688  0.58478457]
  [ 1.9791356   1.259461    1.3853153   0.4061597   0.6920991
   -0.5943369  -0.04056727 -1.2313815 ]
  [-0.39880443 -1.3446653   1.5512997  -0.59888023  0.6662247
    0.516074   -0.43743482 -1.5573683 ]
  [ 1.6826576   0.38080284  0.8525907  -1.0354656  -1.4238155
   -0.00352974 -0.69525635 -1.1990095 ]]], shape=(2, 4, 8), dtype=float32)
(4, 8)
(8,)
()
(1,)
tf.Tensor(
[[-0.09535595 -1.3481662  -0.44069862 -1.4237616   1.3450791   1.1235632
  -1.9858646   1.0657926 ]
 [

### tf.boolean_mask

In [12]:
a = tf.random.normal([4, 28, 28, 3])
print(tf.boolean_mask(a, mask=[True, True, False, False]).shape)
print(tf.boolean_mask(a, mask=[True, True, False], axis=3).shape)
a = tf.ones([2, 3, 4])
print(tf.boolean_mask(a, mask=[[True, True, True],[True, True, False]]))

(2, 28, 28, 3)
(4, 28, 28, 2)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(5, 4), dtype=float32)
