In [2]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

In [3]:
a = tf.random.normal([4, 28, 28, 3])
# print(a)
print(a.shape, a.ndim)
print(tf.reshape(a, [4, 784, 3]).shape)
print(tf.reshape(a, [4, -1, 3]).shape)
print(tf.reshape(a, [4, 784 * 3]).shape)
print(tf.reshape(a, [4, -1]).shape)

(4, 28, 28, 3) 4
(4, 784, 3)
(4, 784, 3)
(4, 2352)
(4, 2352)


### 转置

In [4]:
a = tf.random.normal([4, 3, 2, 1])
print(a.shape)
print(tf.transpose(a).shape) #转置
print(tf.transpose(a, perm=[0, 1, 3, 2]).shape) # 

(4, 3, 2, 1)
(1, 2, 3, 4)
(4, 3, 1, 2)


### 增加维度

In [5]:
a = tf.random.normal([4, 35, 8])
print(tf.expand_dims(a, axis=0).shape)
print(tf.expand_dims(a, axis=1).shape)
print(tf.expand_dims(a, axis=-1).shape)
print(tf.expand_dims(a, axis=-4).shape)

(1, 4, 35, 8)
(4, 1, 35, 8)
(4, 35, 8, 1)
(1, 4, 35, 8)


### 减少维度

In [6]:
print(tf.squeeze(tf.zeros([1, 2, 1, 1, 3])).shape)
a = tf.zeros([1, 2, 1, 3])
print(tf.squeeze(a, axis=0).shape)
print(tf.squeeze(a, axis=2).shape)
print(tf.squeeze(a, axis=-2).shape)
print(tf.squeeze(a, axis=-4).shape)

(2, 3)
(2, 1, 3)
(1, 2, 3)
(1, 2, 3)
(2, 1, 3)


### 维度扩张(没有复制数据)

In [10]:
x = tf.random.normal([4, 28, 28, 3])
print((x + tf.random.normal([3])).shape)
print((x + tf.random.normal([1, 28, 1])).shape)
print((x + tf.random.normal([4, 1, 1, 1])).shape)
# print((x + tf.random.normal([1, 4, 1, 1])).shape)

(4, 28, 28, 3)
(4, 28, 28, 3)
(4, 28, 28, 3)


In [7]:
a = tf.ones([3, 4])
a1 = tf.broadcast_to(a, [2, 3, 4])
print(a1)
a2 = tf.expand_dims(a, axis=0)
print(a2)
a2 = tf.tile(a1, [2, 1, 1])
print(a2)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 3, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(4, 3, 4), dtype=float32)
