In [1]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

### +-*/

In [20]:
b = tf.fill([2, 2], 2.)
a = tf.ones([2, 2])
print('+', a + b)
print('-', a - b)
print('*', a * b)
print('/', a / b)

+ tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)
- tf.Tensor(
[[-1. -1.]
 [-1. -1.]], shape=(2, 2), dtype=float32)
* tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
/ tf.Tensor(
[[0.5 0.5]
 [0.5 0.5]], shape=(2, 2), dtype=float32)


### // %

In [3]:
print('//', b // a)
print('%', b % a)

// tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
% tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [16]:
print(a)
# b = tf.fill([2, 2], 4.0)
print(tf.math.log(a)) # log_e
print(tf.math.log(tf.constant(4.0))) # dtype 必须是float

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(1.3862944, shape=(), dtype=float32)


In [18]:
tf.math.log(8.)/tf.math.log(2.)

<tf.Tensor: id=53, shape=(), dtype=float32, numpy=3.0>

In [19]:
b = tf.fill([2, 2], 2.)
print(tf.pow(b, 3))
print(b ** 3)
print(tf.sqrt(b)) # 开方

tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.4142135 1.4142135]
 [1.4142135 1.4142135]], shape=(2, 2), dtype=float32)


In [21]:
a@b # 矩阵乘法

<tf.Tensor: id=72, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [22]:
tf.matmul(a, b)

<tf.Tensor: id=73, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>