In [1]:
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

In [2]:
a = tf.random.normal([3, 3])
a

<tf.Tensor: id=5, shape=(3, 3), dtype=float32, numpy=
array([[ 0.8686579 , -0.9442523 ,  0.26773518],
       [-1.0057443 , -0.63437366,  0.01646718],
       [-0.6501652 , -0.8413568 , -0.15972652]], dtype=float32)>

In [4]:
mask = a > 0
mask

<tf.Tensor: id=9, shape=(3, 3), dtype=bool, numpy=
array([[ True, False,  True],
       [False, False,  True],
       [False, False, False]])>

In [5]:
tf.boolean_mask(a, mask)

<tf.Tensor: id=36, shape=(3,), dtype=float32, numpy=array([0.8686579 , 0.26773518, 0.01646718], dtype=float32)>

In [6]:
# 坐标
indices = tf.where(mask)
indices

<tf.Tensor: id=37, shape=(3, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [1, 2]])>

In [9]:
# 根据坐标取值
tf.gather_nd(a, indices)

<tf.Tensor: id=41, shape=(3,), dtype=float32, numpy=array([0.8686579 , 0.26773518, 0.01646718], dtype=float32)>

In [10]:
tf.gather(a, indices)

<tf.Tensor: id=43, shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 0.8686579 , -0.9442523 ,  0.26773518],
        [ 0.8686579 , -0.9442523 ,  0.26773518]],

       [[ 0.8686579 , -0.9442523 ,  0.26773518],
        [-0.6501652 , -0.8413568 , -0.15972652]],

       [[-1.0057443 , -0.63437366,  0.01646718],
        [-0.6501652 , -0.8413568 , -0.15972652]]], dtype=float32)>

In [11]:
mask

<tf.Tensor: id=9, shape=(3, 3), dtype=bool, numpy=
array([[ True, False,  True],
       [False, False,  True],
       [False, False, False]])>

In [12]:
A = tf.ones([3, 3])
B = tf.zeros([3, 3])

In [13]:
# true 取A False 取B
tf.where(mask, A, B)

<tf.Tensor: id=50, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [14]:
# scatter_nd
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9, 10, 11, 12])
shape = tf.constant([8])
tf.scatter_nd(indices, updates, shape)

<tf.Tensor: id=54, shape=(8,), dtype=int32, numpy=array([ 0, 11,  0, 10,  9,  0,  0, 12], dtype=int32)>

In [15]:
indices = tf.constant([[0], [2]])
updates = tf.constant([[5], [6], [7], [8]])
shape = tf.constant([4, 4, 4])

In [16]:
updates.shape

TensorShape([4, 1])

In [18]:
updates = tf.broadcast_to(updates, [2, 4, 4])

In [19]:
tf.scatter_nd(indices, updates, shape)

<tf.Tensor: id=62, shape=(4, 4, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

In [22]:
import numpy as np
# np.linspace(2, 2, 2)

array([2., 2.])

In [26]:
y = tf.linspace(-2., 2, 5)
y

<tf.Tensor: id=77, shape=(5,), dtype=float32, numpy=array([-2., -1.,  0.,  1.,  2.], dtype=float32)>

In [27]:
x = tf.linspace(-2., 2, 5)
x

<tf.Tensor: id=81, shape=(5,), dtype=float32, numpy=array([-2., -1.,  0.,  1.,  2.], dtype=float32)>

In [28]:
 points_x, points_y = tf.meshgrid(x, y)

In [34]:
# stack 合并的维度
tf.stack([points_x, points_y], axis=1)

<tf.Tensor: id=105, shape=(5, 2, 5), dtype=float32, numpy=
array([[[-2., -1.,  0.,  1.,  2.],
        [-2., -2., -2., -2., -2.]],

       [[-2., -1.,  0.,  1.,  2.],
        [-1., -1., -1., -1., -1.]],

       [[-2., -1.,  0.,  1.,  2.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[-2., -1.,  0.,  1.,  2.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[-2., -1.,  0.,  1.,  2.],
        [ 2.,  2.,  2.,  2.,  2.]]], dtype=float32)>

In [33]:
[points_x, points_y]

[<tf.Tensor: id=99, shape=(5, 5), dtype=float32, numpy=
 array([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]], dtype=float32)>,
 <tf.Tensor: id=100, shape=(5, 5), dtype=float32, numpy=
 array([[-2., -2., -2., -2., -2.],
        [-1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.,  2.]], dtype=float32)>]

In [41]:
points_x[:, 0]

<tf.Tensor: id=128, shape=(5,), dtype=float32, numpy=array([-2., -2., -2., -2., -2.], dtype=float32)>

In [36]:
points_x[..., 1]

<tf.Tensor: id=113, shape=(5,), dtype=float32, numpy=array([-1., -1., -1., -1., -1.], dtype=float32)>

In [42]:
tf.math.sin(points_x[:, 0])

<tf.Tensor: id=133, shape=(5,), dtype=float32, numpy=
array([-0.9092974, -0.9092974, -0.9092974, -0.9092974, -0.9092974],
      dtype=float32)>